spring: 
  profiles: 
    active: 
      -dev
---
spring: 
  profiles: dev
    application: ss
      name: microservicecloud-config-atguigu-dev
---
spring: 
  profiles: test
      application: ss
      name: microservicecloud-config-atguigu-test